version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  src:
    build:
      context: .
    container_name: src_app
    env_file:
      - .env
    depends_on:
      - minio
      - rabbitmq
      - db
    command: ["src/docker/src.sh"]
    ports:
      - "8000:8000"

  worker:
    build: worker/.
    container_name: worker
    env_file:
      - .env
    depends_on:
      - minio
      - rabbitmq
      - db
      - src





volumes:
  minio_storage: {}
